# main.yml


name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *


jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
              wget https://raw.githubusercontent.com/pexcn/daily/gh-pages/pac/whitelist.pac
              sed -i 's/127.0.0.1:1080/127.0.0.1:7890/' whitelist.pac
              mv whitelist.pac test.pac
              
      - name: Release apk

        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/Kirby97/releases/test/"
          asset_path: ./test.pac
          asset_name: test.pac
          asset_content_type: application/x-ns-proxy-autoconfig
