# main.yml


name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *


jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    steps:
      - name: Checkin
        run: |
              wget https://raw.githubusercontent.com/pexcn/daily/gh-pages/pac/whitelist.pac
              sed -i 's/127.0.0.1:1080/127.0.0.1:7890/' whitelist.pac
              mv whitelist.pac test.pac
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: test
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
        
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              
      - name: Release apk

        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./test.pac
          asset_name: test.pac
          asset_content_type: application/x-ns-proxy-autoconfig
