# main.yml


name: Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 4 * * *

# 这个工作流程需要执行的任务
jobs:
  process:
    name: all process
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      - name: Checkin
        run: |
              wget https://raw.githubusercontent.com/pexcn/daily/gh-pages/pac/whitelist.pac
              sed -i 's/127.0.0.1:1080/127.0.0.1:7890/' whitelist.pac
              mv whitelist.pac test.pac
              
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "test.pac"
          token: ${{ secrets.RELEASE_TOKEN }}
